"""Build a deterministic Factorio scenario containing the FLE Lua runtime.

Factorio serializes ``storage`` but forbids functions inside it.  FLE historically
installed action functions over RCON into ``storage.actions``, which also meant a
multiplayer client joining later could not reconstruct the server's script state.
This compiler moves callables into control.lua locals and leaves storage as data.
"""

from __future__ import annotations

import re
import shutil
import json
import zipfile
import hashlib
from pathlib import Path


RUNTIME_INTERFACE = "fle_runtime"
RUNTIME_MOD_NAME = "fle-runtime"
RUNTIME_MOD_VERSION = "0.1.0"

_LIBRARY_ORDER = (
    "initialise.lua",
    "lualib_util.lua",
    "utils.lua",
    "alerts.lua",
    "objective_telemetry.lua",
    "connection_points.lua",
    "recipe_fluid_connection_mappings.lua",
    "serialize.lua",
    "serialize_direction_fix.lua",
)


def _tool_scripts(tools_dir: Path) -> list[Path]:
    scripts: list[Path] = []
    for directory in sorted(path for path in tools_dir.rglob("*") if path.is_dir()):
        if (
            not (directory / "client.py").is_file()
            or not (directory / "server.lua").is_file()
        ):
            continue
        scripts.extend(
            sorted(
                directory.glob("*.lua"),
                key=lambda path: (path.name == "server.lua", path.name),
            )
        )
    return scripts


def runtime_sources(env_dir: Path) -> list[Path]:
    mods_dir = env_dir / "mods"
    tools_dir = env_dir / "tools"
    libraries = [mods_dir / name for name in _LIBRARY_ORDER]
    missing = [str(path) for path in libraries if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Missing FLE Lua libraries: {', '.join(missing)}")
    return libraries + _tool_scripts(tools_dir)


def _transform_source(source: str, owner: str) -> str:
    """Redirect callable registries and event registration to local runtime APIs."""

    source = source.replace("storage.actions", "fle_actions")
    source = source.replace("storage.utils", "fle_utils")
    source = source.replace("storage.get_alerts", "fle_runtime.get_alerts")
    source = re.sub(
        r"\bscript\.on_event\s*\(",
        f"fle_on_event({owner!r}, ",
        source,
    )
    source = re.sub(
        r"\bscript\.on_nth_tick\s*\(",
        f"fle_on_nth_tick({owner!r}, ",
        source,
    )
    return source


def _runtime_header(observer_name: str) -> str:
    escaped_name = observer_name.replace("\\", "\\\\").replace('"', '\\"')
    return f'''-- Generated by fle.cluster.runtime_scenario. Do not edit this copy.
fle_actions = {{}}
fle_utils = {{}}
fle_runtime = {{}}
fle_event_handlers = {{}}
fle_nth_handlers = {{}}

local function fle_replace_handler(registry, key, owner, handler)
    local handlers = registry[key] or {{}}
    for index = #handlers, 1, -1 do
        if handlers[index].owner == owner then table.remove(handlers, index) end
    end
    if handler then table.insert(handlers, {{owner=owner, handler=handler}}) end
    registry[key] = handlers
end

local function fle_dispatch_event(event)
    for _, entry in ipairs(fle_event_handlers[event.name] or {{}}) do
        entry.handler(event)
    end
end

local function fle_on_event(owner, event_ids, handler, filters)
    if type(event_ids) ~= "table" then event_ids = {{event_ids}} end
    for _, event_id in ipairs(event_ids) do
        fle_replace_handler(fle_event_handlers, event_id, owner, handler)
        -- Register without filters because multiplexed handlers may have different filters.
        script.on_event(event_id, fle_dispatch_event)
    end
end

local function fle_on_nth_tick(owner, tick, handler)
    fle_replace_handler(fle_nth_handlers, tick, owner, handler)
    script.on_nth_tick(tick, function(event)
        for _, entry in ipairs(fle_nth_handlers[tick] or {{}}) do
            entry.handler(event)
        end
    end)
end

fle_observer_name = "{escaped_name}"
fle_observer_group = "fle-observers"
fle_mutation_actions = {{
    "admin_action", "begin_mining", "begin_mining_terrain", "build",
    "build_rail", "build_terrain", "cancel_craft", "cancel_deconstruct",
    "cancel_research", "cancel_upgrade", "change_arithmetic_combinator_parameters",
    "change_decider_combinator_parameters", "change_entity_label", "change_item_label",
    "change_multiplayer_config", "change_riding_state", "change_shooting_state",
    "change_train_stop_station", "change_train_wait_condition",
    "change_train_wait_condition_data", "connect_rolling_stock", "copy_entity_settings",
    "craft", "create_blueprint_like", "cursor_split", "cursor_transfer",
    "delete_blueprint_library", "destroy_opened_item", "disconnect_rolling_stock",
    "drag_train_schedule", "drop_item", "edit_custom_tag", "fast_entity_split",
    "fast_entity_transfer", "flush_opened_entity_fluid",
    "flush_opened_entity_specific_fluid", "go_to_train_station", "import_blueprint",
    "import_blueprint_string", "inventory_split", "inventory_transfer",
    "launch_rocket", "market_offer", "paste_entity_settings", "place_equipment",
    "remove_cables", "remove_train_station", "reset_assembling_machine",
    "rotate_entity", "set_circuit_condition", "set_circuit_mode_of_operation",
    "set_entity_color", "set_filter", "set_infinity_container_filter_item",
    "set_infinity_pipe_filter", "set_inserter_max_stack_size", "set_inventory_bar",
    "set_logistic_filter_item", "set_recipe", "set_request_from_buffers", "set_signal",
    "set_splitter_priority", "set_train_limit", "setup_assembling_machine",
    "setup_blueprint", "spawn_item", "stack_split", "stack_transfer",
    "start_repair", "start_research", "switch_constant_combinator_state",
    "switch_power_switch_state", "take_equipment", "toggle_driving",
    "toggle_entity_logistic_requests", "toggle_map_editor", "undo", "upgrade",
    "use_artillery_remote", "use_item", "use_spidertron_remote"
}}

local function fle_apply_observer_policy(player)
    if not player or player.name ~= fle_observer_name then return false end
    local group = game.permissions.get_group(fle_observer_group)
    if not group then group = game.permissions.create_group(fle_observer_group) end
    for _, name in ipairs(fle_mutation_actions) do
        local action = defines.input_action[name]
        if action then group.set_allows_action(action, false) end
    end
    local old_character = player.character
    player.set_controller{{type=defines.controllers.spectator}}
    if old_character and old_character.valid then old_character.destroy() end
    group.add_player(player)
    local agent = storage.agent_characters and storage.agent_characters[1]
    if agent and agent.valid then player.teleport(agent.position, agent.surface) end
    player.print("FLE observer mode: read-only spectator.")
    return true
end

fle_on_event("fle-observer", defines.events.on_player_joined_game, function(event)
    fle_apply_observer_policy(game.get_player(event.player_index))
end)
'''


def _runtime_footer() -> str:
    return f'''
if not remote then error("FLE runtime: remote API is unavailable") end
if not remote.add_interface then
    error("FLE runtime: remote.add_interface is unavailable (remote=" .. type(remote) .. ")")
end
remote.add_interface("{RUNTIME_INTERFACE}", {{
    dispatch = function(action_name, ...)
        local action = fle_actions[action_name]
        if not action then error("Unknown FLE action: " .. tostring(action_name)) end
        return action(...)
    end
}})
fle_actions.__call_util = function(util_name, ...)
    local utility = fle_utils[util_name]
    if not utility then error("Unknown FLE utility: " .. tostring(util_name)) end
    return utility(...)
end
fle_actions.__dispatch_serialized = function(action_name, ...)
    local action = fle_actions[action_name]
    if not action then error("Unknown FLE action: " .. tostring(action_name)) end
    local ok, result = pcall(action, ...)
    return dump({{a=ok, b=result}})
end
fle_actions.__get_alerts = function(seconds)
        if not fle_runtime.get_alerts then return {{}} end
        return fle_runtime.get_alerts(seconds)
end
fle_actions.__set_fast = function(value)
    storage.fast = value and true or false
    return storage.fast
end
fle_actions.__get_elapsed_ticks = function() return storage.elapsed_ticks or 0 end
fle_actions.__reset_elapsed_ticks = function() storage.elapsed_ticks = 0 end
fle_actions.__agent_character_count = function()
    return storage.agent_characters and #storage.agent_characters or 0
end
fle_actions.__clear_camera = function() storage.camera = nil end
fle_actions.__semantic_event = function(since_tick, wanted)
    for _, event in ipairs(storage.semantic_events or {{}}) do
        if event.tick > since_tick and wanted[event.type] then return event end
    end
    return {{}}
end
fle_actions.__follow_agent = function(player_name)
    local player = game.get_player(player_name)
    local agent = storage.agent_characters and storage.agent_characters[1]
    if player and agent and agent.valid then
        player.teleport(agent.position, agent.surface)
        return true
    end
    return false
end
fle_actions.__observer_status = function()
    local player = game.get_player(fle_observer_name)
    local group = game.permissions.get_group(fle_observer_group)
    local action_count = 0
    for _ in pairs(fle_actions) do action_count = action_count + 1 end
    return {{
        runtime=true,
        action_count=action_count,
        name=fle_observer_name,
        connected=player and player.connected or false,
        spectator=player and player.controller_type == defines.controllers.spectator or false,
        read_only=group and not group.allows_action(defines.input_action.build)
            and not group.allows_action(defines.input_action.craft) or false
    }}
end
'''


def runtime_build_id(env_dir: Path) -> str:
    digest = hashlib.sha256(Path(__file__).read_bytes())
    for path in runtime_sources(env_dir):
        digest.update(path.relative_to(env_dir).as_posix().encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def compile_control(base_control: str, env_dir: Path, observer_name: str) -> str:
    # Register the stable interface before loading action sources. The closures
    # reference the registry tables populated by the remaining sections.
    sections = [
        base_control.rstrip(),
        _runtime_header(observer_name).rstrip(),
        _runtime_footer().rstrip(),
    ]
    for path in runtime_sources(env_dir):
        owner = path.relative_to(env_dir).as_posix()
        transformed = _transform_source(path.read_text(encoding="utf-8"), owner)
        # An IIFE isolates source locals and contains module-style top-level
        # returns (notably lualib_util.lua) without terminating control.lua.
        sections.append(
            f"-- BEGIN {owner}\n;(function()\n{transformed.rstrip()}\nend)()\n"
            f"-- END {owner}"
        )
    sections.append(
        f"fle_actions.__build_id = function() return '{runtime_build_id(env_dir)}' end"
    )
    return "\n\n".join(sections) + "\n"


def stage_runtime_scenarios(
    source_dir: Path,
    destination_dir: Path,
    env_dir: Path,
    scenario: str,
    observer_name: str,
) -> Path:
    """Copy packaged scenarios and compile FLE into the selected scenario."""

    if not source_dir.is_dir():
        raise ValueError(f"Scenarios directory '{source_dir}' does not exist.")
    if destination_dir.exists():
        shutil.rmtree(destination_dir)
    shutil.copytree(source_dir, destination_dir)

    scenario_dir = destination_dir / scenario
    control_path = scenario_dir / "control.lua"
    if not control_path.is_file():
        raise ValueError(f"Scenario '{scenario}' has no control.lua.")
    control_path.write_text(
        compile_control(
            control_path.read_text(encoding="utf-8"), env_dir, observer_name
        ),
        encoding="utf-8",
        newline="\n",
    )
    # Packaged scenarios may contain bytecode compiled from the original
    # control.lua. Leaving it present makes Factorio ignore the generated source.
    compiled_script = scenario_dir / "script.dat"
    if compiled_script.exists():
        compiled_script.unlink()
    return destination_dir


def stage_runtime_mod(destination_dir: Path, env_dir: Path, observer_name: str) -> Path:
    """Build the generated runtime as a local mod shared by server and observer."""

    destination_dir.mkdir(parents=True, exist_ok=True)
    for stale in destination_dir.glob(f"{RUNTIME_MOD_NAME}_*.zip"):
        stale.unlink()
    archive = destination_dir / f"{RUNTIME_MOD_NAME}_{RUNTIME_MOD_VERSION}.zip"
    root = f"{RUNTIME_MOD_NAME}_{RUNTIME_MOD_VERSION}"
    info = {
        "name": RUNTIME_MOD_NAME,
        "version": RUNTIME_MOD_VERSION,
        "title": "FLE Runtime",
        "author": "Factorio Agent Bench",
        "factorio_version": "2.0",
        "dependencies": ["base >= 2.0.77"],
    }
    entries = {
        f"{root}/info.json": json.dumps(info, indent=2) + "\n",
        f"{root}/control.lua": compile_control("", env_dir, observer_name),
    }
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for name, content in entries.items():
            item = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            item.compress_type = zipfile.ZIP_DEFLATED
            item.external_attr = 0o644 << 16
            bundle.writestr(item, content.encode("utf-8"))
    return archive
